### PR TITLE
Write explainer

### PR DESCRIPTION
**Pull request by mattdean-digicatapult**
Implemented te write explainer and adds button to go back to main menu after the explainer has finished

Screen Shot 2022-09-13 at 17 12 08
Screen Shot 2022-09-13 at 17 12 46

### CODE REVIEW

**Review by n3op2 — APPROVED** [review]

**Comment by n3op2** [comment]
Is morello 'desktop' intentional?

**Comment by mattdean-digicatapult** [comment]
@n3op2 what do you mean?

**Comment by mattdean-digicatapult** [comment]
I think I got it, it was the back button background right. I've also done something about the janky side button animation and removed the blue header color on the hacker app (I personally think it looks better now). Going to stop messing about now and get this merged

Screen Shot 2022-09-14 at 11 13 43


Screen Shot 2022-09-14 at 11 13 01

**Comment by jonmattgray** [comment]
On slide 7 and 8 I think there's inconsistency of the entered username. Either the entered username should be `root` or `eve` on both those slides? And the `root` = `root` check underneath should be consistent with what's been entered above it

**Review by jonmattgray — APPROVED** [review]

**Pull request merged**
